image: ruby:2.7

workflow:
  rules:
    - if: "$CI_COMMIT_BRANCH"

pages:
  stage: deploy
  script:
    - mv .public public
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == "development"'
